[package]
name = "rad_db-structure"
version = "0.1.0"
authors = ["Joshua Radin <jradn16@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rad_db-types = { path = "../rad_db-types"}
memmap = "0.7.0"